title: "Abhishek's Profile"
author: "Abhishek Jadhav"
logo: ""
execute:
  execute_notebooks: "off"

myst_enable_extensions:
  - linkify
  - jupyter
  - raw_html
  - html_image

html:
  output_folder: docs
  baseurl: /Classification_book/
  use_repository_button: true

repository:
  url: https://github.com/abhi-dataprofile/Customer_jupyter-book
  path_to_book: ./
  branch: main



